# Generated by Django 3.0.6 on 2022-09-08 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posTitle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empFirtsName', models.CharField(max_length=50)),
                ('empLastName', models.CharField(max_length=50)),
                ('empCode', models.CharField(max_length=3)),
                ('empPhoneNum', models.CharField(max_length=10)),
                ('empEmail', models.EmailField(max_length=50)),
                ('empRegisterDate', models.DateField(auto_now_add=True)),
                ('empPosition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees_CRUD.Position')),
            ],
        ),
    ]
